services:
  - type: web
    name: feature-review-sankey
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.sankey:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
